name: bitpit
markdown: redcarpet
highlighter: rouge
baseurl: /bitpit
timezone: Europe/Rome

exclude: [_manual]

collections:
  modules:
    output: true

sections:
    #modules:
    #    name: Modules
    #
    #    subsections:
    #        overview:
    #            name: Overview
    #            url: overview.html
    #        PABLO:
    #            name: PABLO
    #            url: PABLO.html
    #        RBF:
    #            name: RBF
    #            url: RBF.html

    modules:
        name: Overview
        url: index.html

    documentation:
        name: Documentation

        subsections:
            installation:
                name: Installation guide
                url: installation.html
            manual:
                name: Programmer's manual
                url: manual/1.5.0/index.html

    downloads:
        name: Downloads
        url:

# Some gems, like jekyll-mentions, need to parse single html files. If those
# file contain closing divs (which were open elsewhere) the parser will see
# there's an extra div and remove it as it was never opened. When generating
# the programmer's manual we open some divs in a header.html file and close
# them in a separate footer.html file. For being able to generate the
# programmer's manual these gems cannot be used.
gems:
   - jekyll-coffeescript
   - jekyll-paginate
